### PR TITLE
Fix/swap improvements

### PR DESCRIPTION
**Pull request by antonijzelinskij**
#86932yu6p
#86932e4mq
#869333y24
#86931z5ff

### CODE REVIEW

**Comment by stepanLav** [comment]
Task linked: [CU-869333y24 Android: Wrong insufficient balance dialog info](https://app.clickup.com/t/869333y24)

**Comment by stepanLav** [comment]
Task linked: [CU-86932e4mq Android. After setting other token for fee it doesn't change on Confirm screen](https://app.clickup.com/t/86932e4mq)

**Comment by stepanLav** [comment]
Task linked: [CU-86932yu6p Android. Reset fee token to default when change between self-sufficient token to pay](https://app.clickup.com/t/86932yu6p)

**Comment by stepanLav** [comment]
Task linked: [CU-86931z5ff Android. System back is not working](https://app.clickup.com/t/86931z5ff)

**Review by valentunn — APPROVED** [review]

**Pull request merged**
