### PR TITLE
Fixed crash after change wallet

### PR DESCRIPTION
**Pull request by antonijzelinskij**
#8692t85a6

### CODE REVIEW

**Comment by stepanLav** [comment]
Task linked: [CU-8692t85a6 Android. Crash after switching accounts and go to Send](https://app.clickup.com/t/8692t85a6)

**Review by valentunn — APPROVED** [review]
Can you explain the cause of the crash?

**Comment by antonijzelinskij** [comment]
> Can you explain the cause of the crash?

I'm not sure because didn't catch it on android. But the logs in the task tells that the crash happens since RecyclerView is null during call

**Comment by valentunn** [comment]
> > Can you explain the cause of the crash?
> 
> I'm not sure because didn't catch it on android. But the logs in the task tells that the crash happens since RecyclerView is null during call

In that case `observeWhenCreated` wont actually change much since `observe` we're using is an extension for `launchWhenResumed` which happens even later in lifecycle

**Pull request merged**
